NoMethodError in web UI: handle nil @checks
Reproduce:
1. flush your DB: `redis-cli -h localhost -p 6379 flushdb`

2. create a new contact
```
Flapjack::Diner.create_contacts({
  id: '90da114e-3968-418f-8c3c-f9b8e13645f9',
  name: 'Foo Bar'
})
```

3. visit `/contacts/90da114e-3968-418f-8c3c-f9b8e13645f9`

You will get "undefined method `empty?' for nil:NilClass" because @checks == nil